name: Build & Push Docker Image

on:
  push:
    branches:
      - main
      - "*"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    env:
      IMAGE_NAME: ${{ github.repository }}
      TEST_MODE: ${{ github.ref != 'refs/heads/main' }}
      PUSH: ${{ !contains(github.event_name, 'pull_request') && env.TEST_MODE != 'true' }}
      LOAD: ${{ !contains(github.event_name, 'pull_request') || env.TEST_MODE != 'true' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Debug
        run: |
          echo "github ref: ${{ github.ref }}"
          echo "github event: ${{ github.event_name }}"
          echo "repository: ${{ github.repository }}"
          echo "test mode: ${{ env.TEST_MODE }}"
          echo ""
          echo "push: ${{ PUSH }}"
          echo "load: ${{ LOAD }}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare
        id: prep
        run: |
          REPO=${GITHUB_REPOSITORY,,}
          echo "repository=${REPO}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ PUSH }}
          load: ${{ LOAD }}
          tags: |
            ghcr.io/${{ steps.prep.outputs.repository }}:latest
            ghcr.io/${{ steps.prep.outputs.repository }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        if: ${{ PUSH }}
        with:
          subject-name: ghcr.io/${{ github.repository }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
